<a href="https://colab.research.google.com/github/sheCodesAI/data-analysis-projects/blob/main/CensusDataset3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv(r"/content/6. India Census 2011.csv")

In [ ]:
data.head(2)

,District_code,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,214866,162578,52288,...,1489,5559,47,6,66459,41367,27950,503223,160933,88978

## **1. how will you hide the indexes of dataframe?**

In [ ]:
data.head(2).style.hide(axis="index")

## **2. how can we set the caption or heading in df**

In [ ]:
data.head(2).style.set_caption('india sensus 2011 dataset')

In [ ]:
data.head(2).style.set_caption('india sensus 2011 dataset')

## **3. show records related with districts : New Delhi, Jaipur, Lucknow**

In [ ]:
data[data['District_name'].isin(['Jaipur', 'Lucknow', 'New Delhi'])]

,District_code,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
93,94,NCT OF DELHI,New Delhi,142004,77942,64062,114179,59541,46940,12601,...,4852,2933,312,679,15942,17742,23934,76076,43913,21773
109,110,RAJASTHAN,Jaipur,6626178,3468507,3157671,4300965,2464893,1714947,749946,...,12708,18782,1020,81079,659389,455527,703673,4091148,1646480,884057
156,157,UTTAR PRADESH,Lucknow,4589838,2394476,2195362,3127260,1542806,1226399,316407,...,20493,23883,3877,4975,428121,378742,639260,2678289,1161686,685258

## **4. Calculate state wise:**
### **a. Total no. of population**
### **b. total no. of population with different regions**

In [ ]:
data.head(2)

,District_code,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,214866,162578,52288,...,1489,5559,47,6,66459,41367,27950,503223,160933,88978

In [126]:
data.groupby('State_name').Population.sum().sort_values().head()

State_name
LAKSHADWEEP                     64473
DAMAN AND DIU                  243247
DADRA AND NAGAR HAVELI         343709
ANDAMAN AND NICOBAR ISLANDS    380581
SIKKIM                         610577
Name: Population, dtype: int64

In [ ]:
data.columns

Index(['District_code', 'State_name', 'District_name', 'Population', 'Male',
       'Female', 'Literate', 'Workers', 'Male_Workers', 'Female_Workers',
       'Cultivator_Workers', 'Agricultural_Workers', 'Household_Workers',
       'Hindus', 'Muslims', 'Christians', 'Sikhs', 'Buddhists', 'Jains',
       'Secondary_Education', 'Higher_Education', 'Graduate_Education',
       'Age_Group_0_29', 'Age_Group_30_49', 'Age_Group_50'],
      dtype='object')

In [ ]:
data.groupby('State_name')[['Hindus', 'Muslims', 'Christians', 'Sikhs', 'Buddhists', 'Jains']].sum().sort_values(by = ['Hindus', 'Muslims', 'Christians', 'Sikhs', 'Buddhists', 'Jains']).head(2)

             Hindus  Muslims  Christians  Sikhs  Buddhists  Jains
State_name
LAKSHADWEEP    1788    62268         317      8         10     11
MIZORAM       30136    14832      956331    286      93411    376

## **5. how many male workers in Maharashtra?**

In [ ]:
data.head(1)

,District_code,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679

In [107]:
data[data.State_name == 'MAHARASHTRA']['Male_Workers'].sum()

np.int64(32616875)

## **6. How to set a column as index of the DF**

In [111]:
data = pd.read_csv(r"/content/6. India Census 2011.csv")

In [113]:
data.set_index('District_code', inplace = True)

In [114]:
data.head(3)

,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,Cultivator_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
District_code,,,,,,,,,,,,,,,,,,,,,
1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,34680,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679
2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,214866,162578,52288,55299,...,1489,5559,47,6,66459,41367,27950,503223,160933,88978
3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,75079,53265,21814,20869,...,658,1092,88635,103,16265,8923,6197,70703,41515,21019

## **7.a  Add a suffix to the col names**

In [115]:
data.head(1)

,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,Cultivator_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
District_code,,,,,,,,,,,,,,,,,,,,,
1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,34680,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679

In [123]:
data.add_suffix('_').head(1)

,State_name_,District_name_,Population_,Male_,Female_,Literate_,Workers_,Male_Workers_,Female_Workers_,Cultivator_Workers_,...,Christians_,Sikhs_,Buddhists_,Jains_,Secondary_Education_,Higher_Education_,Graduate_Education_,Age_Group_0_29_,Age_Group_30_49_,Age_Group_50_
District_code,,,,,,,,,,,,,,,,,,,,,
1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,34680,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679

In [124]:
data = data.add_prefix('_').head(1)
# make changes permenantly : assign to data again

,_State_name,_District_name,_Population,_Male,_Female,_Literate,_Workers,_Male_Workers,_Female_Workers,_Cultivator_Workers,...,_Christians,_Sikhs,_Buddhists,_Jains,_Secondary_Education,_Higher_Education,_Graduate_Education,_Age_Group_0_29,_Age_Group_30_49,_Age_Group_50
District_code,,,,,,,,,,,,,,,,,,,,,
1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,34680,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679